version: "3"
services:
    web:
      build:
        context: ./build
      ports:
         - "8080:80"
      volumes:
         - ./config/all.conf:/etc/nginx/conf.d/default.conf
         - ./code:/code
      networks:
         - testing
    php-fpm:
      build:
        context: ./build2
      volumes:
         - ./code:/code
      networks:
         - testing
networks:
    testing:
      driver: bridge
